CC = g++
CFLAGS = -Wall
PROG = final

SRCS = final.cpp
IMG=imageloader.cpp
LIBS = -lglut -lGL -lGLU

all: $(PROG)

$(PROG):	$(SRCS)
	$(CC) $(CFLAGS) -o $(PROG) $(SRCS) $(IMG) $(LIBS)

clean:
	rm -f $(PROG)
